# This workflow will install dependencies, and run black, flake8 and mypy on notebooks
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Jupyter Notebook package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install flake8
        pip install mypy
        pip install -U nbqa
    - name: Run black
      run: black --check .
    - name: Run flake8
      run: flake8
    - name: Run Mypy Predictions
      run: nbqa mypy icecube-predictions.ipynb
    - name: Run Mypy Train
      run: nbqa mypy icecube-train.ipynb

